development:
 TWITTER_KEY: 
 TWITTER_SECRET: 

 GITHUB_ID: 
 GITHUB_SECRET: 

 AWS_BUCKET: 
 AWS_ACCESS_KEY_ID: 
 AWS_SECRET_ACCESS_KEY: 

production:
 TWITTER_KEY: 
 TWITTER_SECRET: 

 GITHUB_ID:
 GITHUB_SECRET: 

 AWS_BUCKET:
 AWS_ACCESS_KEY_ID: 
 AWS_SECRET_ACCESS_KEY: 


