# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:

development:
  TWITTER_KEY:
  TWITTER_SECRET:
  GITHUB_ID:
  GITHUB_SECRET:
  AWS_BUCKET:
  FB_ID:
  FB_Secret:


production:
 TWITTER_KEY:
 TWITTER_SECRET:
 AWS_BUCKET:
 GITHUB_ID:
 GITHUB_SECRET:

 FB_ID:
 FB_Secret:



